"""
Project Name:   HoweLab8_main.py
Purpose:        Reads a cost-of-living CSV file, stores data in
                2D array, adds two new columns (City_Cost_Summary
                and Review_Flag), and writes the updated dataset
                to a new CSV file in a new subdirectory. Includes an
                extra-credit data-cleaning step that removes the unnamed
                index column and rows where Cost_index is 0.0 (invalid/missing data). 
Description:    Reads a cost-of-living CSV file, stores data in
                2D array, adds two new columns (City_Cost_Summary
                and Review_Flag), and writes the updated dataset
                to a new CSV file in a new subdirectory.
                Includes an extra-credit data-cleaning step that
                removes the unnamed index column and rows where
                Cost_index is 0.0 (invalid/missing data).
Created Date:   2026-03-29
Author:         Daniel Howe
Version:        1.4
"""

# Resource Disclosure:
# Dataset: The lab required a CSV from data.gov, but every dataset I found
# there had tens of thousands of rows — too large to verify results by hand.
# I switched to a Kaggle cost-of-living dataset (cities_living_cost.csv),
# which has 224 rows and 57 columns and meets the ≥100 rows / ≥5 columns
# requirement.
# AI assistance: I used Claude to help plan the exception handling strategy
# and help design the data-cleaning algorithm. The core logic (reading the CSV,
# cleaning the data, building the summary column, and writing the output) was 
# written by me using the blueprint I created and the in-class examples.

import csv
import os

# ── Configuration ────────────────────────────────────────────
source_file   = 'cities_living_cost.csv'
output_folder = 'processed_data'
output_file   = os.path.join(output_folder, 'cities_living_cost_updated.csv')

MIN_ROWS    = 100
MIN_COLUMNS = 5

# ── Step 1: Read the source CSV ───────────────────────────────
try:
    with open(source_file, newline='', encoding='utf-8') as csvfile:
        reader = csv.reader(csvfile)
        header = next(reader)
        rows   = list(reader)
except FileNotFoundError:
    print(f'Error: Source file not found — {source_file}')
    raise SystemExit(1)
except PermissionError:
    print(f'Error: Permission denied when reading — {source_file}')
    raise SystemExit(1)
except Exception as e:
    print(f'Error: Could not read source file — {e}')
    raise SystemExit(1)

# ── Step 2: Data Cleaning (Extra Credit) ──────────────────────
# Data-Cleaning Algorithm:
#
# The original Kaggle CSV export contains two categories of
# unwanted data that are removed before any processing occurs:
#
# 1. Remove the unnamed index column (column 0).
#    The first column has no header name and contains only
#    sequential row numbers generated by the Kaggle export tool.
#    This column carries no meaningful information about the cities
#    and is dropped from both the header and every data row.
#    After removal, City shifts to index 0 and Cost_index to index 1.
#
# 2. Remove rows where Cost_index equals 0.0.
#    A Cost_index of 0.0 is not a valid cost-of-living value;
#    it is a placeholder indicating that no cost index data was
#    collected for that city. Keeping these rows would produce
#    misleading summary labels (e.g., "Chemnitz - Index 0.0").
#    Any row whose Cost_index cell (column 1 after step 1) is
#    exactly "0.0" is discarded.
#
# After cleaning, the dataset still satisfies the lab requirements
# (≥100 rows, ≥5 columns).

# 2a. Drop the unnamed index column (column 0)
if header[0].strip() == '':
    header = header[1:]
    rows   = [row[1:] for row in rows]
    print('Cleaning: removed unnamed index column (column 0).')

# 2b. Remove rows where Cost_index (now column 1) is "0.0"
rows_before = len(rows)
rows = [row for row in rows if not (len(row) > 1 and row[1].strip() == '0.0')]
rows_removed = rows_before - len(rows)
print(f'Cleaning: removed {rows_removed} rows with invalid Cost_index (0.0).')
print(f'Cleaning: {len(rows)} rows remain after cleaning.')

# ── Step 3: Validate the file ─────────────────────────────────
if len(rows) < MIN_ROWS:
    print(f'Error: Source file has only {len(rows)} data rows; at least {MIN_ROWS} required.')
    raise SystemExit(1)

if len(header) < MIN_COLUMNS:
    print(f'Error: Source file has only {len(header)} columns; at least {MIN_COLUMNS} required.')
    raise SystemExit(1)

# ── Step 4: Build updated header ─────────────────────────────
updated_header = header + ['City_Cost_Summary', 'Review_Flag']

# ── Step 5: Process each row ──────────────────────────────────
# Column layout after cleaning (0-indexed):
#   col 0 → City
#   col 1 → Cost_index
updated_rows = []

for row in rows:
    # Skip rows that are completely empty
    if not any(cell.strip() for cell in row):
        continue

    try:
        city       = row[0].strip()
        cost_index = row[1].strip()

        # Validate that cost_index is a real number
        float(cost_index)

        summary_value = f'{city} - Index {cost_index}'
        updated_row   = row + [summary_value, '-1']
        updated_rows.append(updated_row)

    except IndexError:
        print(f'Warning: Skipping row with too few columns: {row}')
    except ValueError:
        print(f'Warning: Skipping row with invalid cost index value: {row}')

# ── Step 6: Create output subdirectory ───────────────────────
try:
    os.makedirs(output_folder, exist_ok=True)
except PermissionError:
    print(f'Error: Permission denied when creating directory — {output_folder}')
    raise SystemExit(1)
except OSError as e:
    print(f'Error: Could not create output directory — {e}')
    raise SystemExit(1)

# ── Step 7: Write the updated CSV ────────────────────────────
try:
    with open(output_file, 'w', newline='', encoding='utf-8') as newcsvfile:
        writer = csv.writer(newcsvfile)
        writer.writerow(updated_header)
        writer.writerows(updated_rows)
except PermissionError:
    print(f'Error: Permission denied when writing — {output_file}')
    raise SystemExit(1)
except OSError as e:
    print(f'Error: Could not write output file — {e}')
    raise SystemExit(1)

print(f'Done. {len(updated_rows)} rows written to {output_file}')
